version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    image: docker.io/library/api
    build: 
      context: .
      dockerfile: GamificationAPI/Dockerfile
    container_name: api
    ports:
      - '8088:80'
    networks:
      - dev

  app_db:
     image: postgres:latest
     container_name: app_db
     hostname: api-db
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=IPgamification
     ports:
      - "5433:5432"
     restart: always
   #  volumes:
   #   - app_data:/var/lib/postgresql/data
     networks:
      - dev

#volumes:
 # app_data: